To array operation dsl
allegro/client-side-logic-dsl pull request #11
Opened 2022-07-01 05:50 UTC by KTGypsy

## What:

* toArray operation dsl -  Splits this char sequence to a list of strings.

## Why:

* to extend standard library possibilities

## Example:

* see unit tests

2022-07-01 08:31 UTC, mkrogulskiallegro2 commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/ToArrayOperation.kt
> +     * @param sequence client side data or operation results which will be injected to string
into string ? (with ?, not sure if that 'more' correct 🤔 to your decision)

2022-07-01 08:31 UTC, mkrogulskiallegro2 approved these changes, later dismissed

2022-07-01 14:46 UTC, PaulinaSadowskaAllegro requested changes

2022-07-01 14:46 UTC, PaulinaSadowskaAllegro commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/ToArrayOperation.kt
> +    fun ClientLogicElement.toArray() = ToArrayOperatorFactory().create(this)
I think this name should be more explicit -  IMO `toCharArray` will be better.

2022-07-01 14:46 UTC, PaulinaSadowskaAllegro commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/ToArrayOperation.kt
> +    fun asArray(sequence: ClientLogicElement) = ToArrayOperatorFactory().create(sequence)
do we need `asArray` function? `toCharArray` wouldn't be enough?

2022-07-04 07:18 UTC, PaulinaSadowskaAllegro approved these changes, later dismissed

2022-07-04 07:19 UTC, mkrogulskiallegro2 submitted a review, later dismissed

2022-07-04 10:20 UTC, PaulinaSadowskaAllegro approved these changes

2022-07-04 10:20 UTC, mkrogulskiallegro2 approved these changes

2022-07-04 10:23 UTC, merged