Replace operation dsl
allegro/client-side-logic-dsl pull request #13
Opened 2022-07-01 05:54 UTC by KTGypsy

## What:

* replace operation dsl -  replaces a given string with the new one

## Why:

* to extend standard library possibilities

## Example:

* see unit tests

2022-07-01 08:28 UTC, mkrogulskiallegro2 requested changes

2022-07-01 08:28 UTC, mkrogulskiallegro2 commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/ReplaceOperation.kt
> +     * @param newString replaced string
replacement string

2022-07-01 14:52 UTC, PaulinaSadowskaAllegro submitted a review, later dismissed

2022-07-04 05:34 UTC, mkrogulskiallegro2 approved these changes

2022-07-04 07:17 UTC, PaulinaSadowskaAllegro approved these changes

2022-07-04 09:35 UTC, merged