Format dsl
allegro/client-side-logic-dsl pull request #22
Opened 2022-07-07 07:27 UTC by piotrolszewski-a

## What:

*Format dsl

## Why:

*

## Example:

*

2022-07-12 10:24 UTC, KTGypsy requested changes

2022-07-12 10:24 UTC, KTGypsy commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/FormatOperation.kt
> +    fun ClientLogicElement.format(vararg args: ClientLogicElement) = FormatOperatorFactory().create(this, args)
not sure if its okay to only allow ClientLogicElements here. User is not able to use any strings numbers etc, only registryKey or lists which can be initiated explicitly

2022-07-12 10:24 UTC, KTGypsy commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/FormatOperation.kt
> +    fun ClientLogicElement.format(vararg args: ClientLogicElement) = FormatOperatorFactory().create(this, args)
it should probably by Any type

2022-07-12 10:24 UTC, KTGypsy commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/FormatOperation.kt
> +                is ClientLogicElement -> elementsListBuilder.add(it)
Check for instance is always 'true'

2022-07-12 10:24 UTC, KTGypsy commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/FormatOperation.kt
> +                is StringElement -> elementsListBuilder.add(it)
these checks should be about primitive types not the CSL ones I think 🤔

2022-07-14 11:08 UTC, PaulinaSadowskaAllegro requested changes

2022-07-14 11:08 UTC, PaulinaSadowskaAllegro commented on src/main/kotlin/pl/allegro/mobile/logic/operators/string/FormatOperation.kt
> +            when (it) {
`when` can be simplified:
```
            when (it) {
                is String -> elementsListBuilder.add(StringElement(it))
                is Number -> elementsListBuilder.add(NumberElement(it))
                is Boolean -> elementsListBuilder.add(BooleanElement(it))
                is ClientLogicElement -> elementsListBuilder.add(it)
            }
```

2022-07-15 05:11 UTC, KTGypsy submitted a review, later dismissed

2022-07-15 09:22 UTC, PaulinaSadowskaAllegro approved these changes

2022-07-15 09:25 UTC, KTGypsy approved these changes

2022-07-15 10:16 UTC, merged