MBOX-4240 add format for case when both params are Exact(0)
allegro/client-side-logic-dsl pull request #25
Opened 2022-09-16 14:17 UTC by lsolniczek

## What:

* add format for case when both params are Exact(0)

## Why:

* Because since now for this case method returns `"%0.0f"` that is not understood by Android

2022-09-16 15:41 UTC, PaulinaSadowskaAllegro requested changes

2022-09-16 15:41 UTC, PaulinaSadowskaAllegro commented on src/main/kotlin/pl/allegro/mobile/logic/operators/numeric/DecimalFormatOperation.kt
> +    @Suppress("MaxLineLength")
Maybe try splitting this method to avoid the warning? E.g. you can extract creation of the `formatString`

2022-09-19 09:26 UTC, mkrogulskiallegro2 approved these changes

2022-09-19 11:55 UTC, PaulinaSadowskaAllegro approved these changes

2022-09-19 12:35 UTC, merged